version: '3.4'

volumes:
  grupo-7-backend:
    external: true

services:
  backend-api-ms:
    container_name: backend-api-ms
    image: backend-api:latest
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: studentDb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d