version: '3.4'

networks:
  grupo-7:

volumes:
  grupo-7-backend:
    external: true

services:
  backend-api-ms:
    container_name: backend-api-ms
    image: backend-api:latest
    ports:
      - 8080:8080
    networks:
      - grupo-7